apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-apache-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
        # Sidecar Container for Monitoring (Bhai, ye Grafana ke liye hai)
        - name: exporter
          image: bitnami/apache-exporter:latest
          ports:
            - containerPort: 9117
